include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/l10n/gen/**
    - android/**
    - ios/**
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - unawaited_futures
    - avoid_dynamic_calls
