import { useEffect, useMemo, useState } from 'react';
import { addCompanyItem, beginCompanyPayment, companyCta, COMPANY_STATUS, deleteCompanyItem, getCompany, submitCompany, updateCompany } from '../lib/company.js';
import { navigate } from '../lib/router.js';
import { useLanguage } from '../lib/i18n.jsx';
import '../company-system.css';

const tabs = [['dashboard','Boshqaruv'],['profile','Profil'],['catalog','Katalog'],['contact','Aloqa'],['settings','Sozlamalar']];
const blankItem = { name: '', category: '', description: '', price: '', promotionPrice: '', imageUrl: '', available: true };

export default function CompanyWorkspacePage({ companyId }) {
  const { t } = useLanguage();
  const [company, setCompany] = useState(undefined);
  const [form, setForm] = useState(null);
  const [tab, setTab] = useState('dashboard');
  const [item, setItem] = useState(blankItem);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState('');
  const load = () => getCompany(companyId).then((data) => { setCompany(data.company); setForm(data.company); }).catch(() => setCompany(null));
  useEffect(() => { load(); }, [companyId]);
  const cta = companyCta(form?.category);
  const topItems = useMemo(() => (form?.catalog || []).slice(0, 4), [form]);

  if (company === undefined) return <main className="cw-state">{t('Workspace yuklanmoqda…')}</main>;
  if (!company) return <main className="cw-state"><h1>{t('Workspace topilmadi')}</h1><p>{t('Bu Company ID sizga tegishli emas yoki sessiya tugagan.')}</p><button onClick={() => navigate('/account')}>{t('Kabinetga qaytish')}</button></main>;

  const save = async () => {
    setBusy(true); setNotice('');
    try { const data = await updateCompany(company.companyId, form); setCompany(data.company); setForm(data.company); setNotice(t('O‘zgarishlar saqlandi')); }
    catch { setNotice(t('Saqlab bo‘lmadi')); } finally { setBusy(false); }
  };
  const sendReview = async () => { setBusy(true); try { await save(); const data = await submitCompany(company.companyId); setCompany(data.company); setForm(data.company); setNotice(t('Ariza admin tekshiruviga yuborildi')); } finally { setBusy(false); } };
  const payment = async () => { setBusy(true); try { const data = await beginCompanyPayment(company.companyId); if (data.payLink) window.location.href = data.payLink; else setNotice(data.message || t('Payme havolasi tayyorlanmoqda')); } catch (err) { setNotice(err.message === 'payments_backend_pending' ? t('Payme kompaniya to‘lovi backend deployidan keyin ochiladi. Admin hozircha faollashtirishi mumkin.') : t('To‘lovni boshlab bo‘lmadi.')); } finally { setBusy(false); } };
  const addItem = async (e) => { e.preventDefault(); setBusy(true); try { const data = await addCompanyItem(company.companyId, item); setCompany(data.company); setForm(data.company); setItem(blankItem); setNotice(t('Katalog elementi qo‘shildi')); } finally { setBusy(false); } };
  const removeItem = async (id) => { if (!confirm(t('Element o‘chirilsinmi?'))) return; const data = await deleteCompanyItem(company.companyId, id); setCompany(data.company); setForm(data.company); };
  const set = (key) => (e) => setForm((old) => ({ ...old, [key]: e.target.value }));

  return <main className="cw-page">
    <header className="cw-header"><button className="cw-brand" onClick={() => navigate('/')}><i>N</i><b>NFCSTORE</b><span>{t('BUSINESS')}</span></button><div className="cw-company"><small>{t('COMPANY ID')}</small><b>{company.companyId}</b><span data-status={company.status}>{t(COMPANY_STATUS[company.status]) || company.status}</span></div><div className="cw-head-actions"><button onClick={() => navigate(`/c/${company.companyId.toLowerCase()}`)}>{t('NFC profil')} ↗</button><button onClick={() => navigate(`/company/${company.companyId.toLowerCase()}`)}>{t('Kompaniya sahifasi')} ↗</button><button onClick={() => navigate('/account')}>{t('Kabinet')}</button></div></header>
    <div className="cw-layout">
      <aside className="cw-sidebar"><div className="cw-owner"><div>{form.logoUrl ? <img src={form.logoUrl} alt="" /> : form.displayName.slice(0,2).toUpperCase()}</div><span><b>{form.displayName}</b><small>{form.city}</small></span></div><nav>{tabs.map(([id,label],index) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}><i>0{index+1}</i>{t(label)}<span>›</span></button>)}</nav><div className="cw-separation"><b>✓ {t('NFC ID’dan alohida')}</b><p>{t('Shaxsiy kartalaringiz bu yerda o‘zgarmaydi.')}</p></div></aside>
      <section className="cw-main">
        <div className="cw-title"><div><span>{t('BUSINESS WORKSPACE')}</span><h1>{t(tabs.find(([id]) => id === tab)?.[1])}</h1></div><button className="cw-save" onClick={save} disabled={busy}>{busy ? t('Saqlanmoqda…') : t('Saqlash')}</button></div>

        {company.status !== 'active' && <div className="cw-status-banner" data-status={company.status}><div><b>{t(COMPANY_STATUS[company.status])}</b><p>{company.status === 'pending_review' ? t('Admin arizani tekshirmoqda. Ma’lumotlarni tahrirlashda davom etishingiz mumkin.') : company.status === 'approved' || company.status === 'payment_pending' ? t('Ariza tasdiqlandi. Company ID ni faollashtirish uchun to‘lovni yakunlang.') : company.status === 'rejected' ? company.rejectedReason || t('Ma’lumotlarni tuzatib, qayta yuboring.') : t('Arizani admin tekshiruviga yuboring.')}</p></div>{['draft','rejected'].includes(company.status) && <button onClick={sendReview}>{t('Tekshiruvga yuborish')}</button>}{['approved','payment_pending'].includes(company.status) && <button onClick={payment}>{t('Payme orqali to‘lash')}</button>}</div>}

        {tab === 'dashboard' && <div className="cw-dashboard"><section className="cw-action-grid"><button onClick={() => navigate(`/c/${company.companyId.toLowerCase()}`)}><i>◉</i><span><small>{t('NFC KARTAGA YOZILADI')}</small><b>{t('Tezkor NFC profil')}</b><p>{t('Bir tegishda aloqa, yo‘nalish va asosiy takliflar.')}</p></span><strong>↗</strong></button><button onClick={() => navigate(`/company/${company.companyId.toLowerCase()}`)}><i>◇</i><span><small>{t('TO‘LIQ PUBLIC SAHIFA')}</small><b>{t('Kompaniya sayti')}</b><p>{t('Katalog, galereya, lokatsiya va to‘liq ma’lumot.')}</p></span><strong>↗</strong></button><button onClick={() => setTab('settings')}><i>⚙</i><span><small>{t('FAQAT EGASI UCHUN')}</small><b>{t('Sozlamalar')}</b><p>{t('Company ID holati, linklar va admin jarayoni.')}</p></span><strong>→</strong></button></section><section className="cw-metrics"><article><small>{t('STATUS')}</small><b>{t(COMPANY_STATUS[company.status])}</b><p>{t('Admin boshqaruvi')}</p></article><article><small>{t('KATALOG')}</small><b>{form.catalog?.length || 0}</b><p>{t(cta.noun)}</p></article><article><small>{t('PUBLIC URL')}</small><b>/company/{company.companyId}</b><p>{t('To‘liq sahifa')}</p></article></section></div>}

        {tab === 'profile' && <div className="cw-panel"><div className="cw-panel-head"><span>01</span><div><h2>{t('Kompaniya profili')}</h2><p>{t('NFC va public sahifada bir xil ma’lumot ishlatiladi.')}</p></div></div><div className="cw-fields"><label><span>{t('Nomi')}</span><input value={form.displayName} onChange={set('displayName')} /></label><label><span>{t('Kichik soha')}</span><input value={form.subcategory || ''} onChange={set('subcategory')} /></label><label className="wide"><span>{t('Biz haqimizda')}</span><textarea value={form.description || ''} onChange={set('description')} /></label><label><span>{t('Logo URL')}</span><input value={form.logoUrl || ''} onChange={set('logoUrl')} placeholder="https://…" /></label><label><span>{t('Muqova rasmi URL')}</span><input value={form.coverUrl || ''} onChange={set('coverUrl')} placeholder="https://…" /></label></div></div>}

        {tab === 'catalog' && <div className="cw-catalog-editor"><div className="cw-panel"><div className="cw-panel-head"><span>01</span><div><h2>{t(cta.noun)}</h2><p>{t('Qo‘shilgan elementlar ikkala kompaniya ko‘rinishida darhol chiqadi.')}</p></div></div><form className="cw-item-form" onSubmit={addItem}><input required value={item.name} onChange={(e) => setItem((old) => ({ ...old, name:e.target.value }))} placeholder={t('Nomi')} /><input value={item.category} onChange={(e) => setItem((old) => ({ ...old, category:e.target.value }))} placeholder={t('Kategoriya')} /><input required type="number" min="0" value={item.price} onChange={(e) => setItem((old) => ({ ...old, price:e.target.value }))} placeholder={t('Narxi')} /><input type="number" min="0" value={item.promotionPrice} onChange={(e) => setItem((old) => ({ ...old, promotionPrice:e.target.value }))} placeholder={t('Aksiya narxi')} /><input className="wide" value={item.imageUrl} onChange={(e) => setItem((old) => ({ ...old, imageUrl:e.target.value }))} placeholder={t('Rasm URL')} /><textarea className="wide" value={item.description} onChange={(e) => setItem((old) => ({ ...old, description:e.target.value }))} placeholder={t('Qisqa tavsif')} /><button disabled={busy}>＋ {t('Qo‘shish')}</button></form></div><div className="cw-items">{(form.catalog || []).map((entry) => <article key={entry.id}><img src={entry.imageUrl || form.coverUrl || '/business-assets/market-interior.jpg'} alt="" /><div><small>{entry.category}</small><b>{entry.name}</b><p>{entry.description}</p><strong>{Number(entry.price).toLocaleString('uz-UZ')} {t('so‘m')}</strong></div><button onClick={() => removeItem(entry.id)}>×</button></article>)}{!form.catalog?.length && <p className="cw-empty">{t('Hozircha element yo‘q. Birinchi mahsulot yoki xizmatni yuqoridan qo‘shing.')}</p>}</div></div>}

        {tab === 'contact' && <div className="cw-panel"><div className="cw-panel-head"><span>01</span><div><h2>{t('Aloqa va lokatsiya')}</h2><p>{t('Mijoz tegishli tugmani bosganda shu ma’lumot ishlatiladi.')}</p></div></div><div className="cw-fields"><label><span>{t('Telefon')}</span><input value={form.phone || ''} onChange={set('phone')} /></label><label><span>Telegram</span><input value={form.telegram || ''} onChange={set('telegram')} /></label><label><span>WhatsApp</span><input value={form.whatsapp || ''} onChange={set('whatsapp')} /></label><label><span>{t('Veb-sayt')}</span><input value={form.website || ''} onChange={set('website')} /></label><label><span>{t('Shahar')}</span><input value={form.city || ''} onChange={set('city')} /></label><label><span>{t('To‘liq manzil')}</span><input value={form.address || ''} onChange={set('address')} /></label></div></div>}

        {tab === 'settings' && <div className="cw-settings"><section><small>{t('COMPANY ID')}</small><h2>{company.companyId}</h2><p>{t('ID o‘zgarmaydi va shaxsiy NFC ID bilan aralashmaydi.')}</p></section><section><small>{t('NFC KARTAGA YOZILADIGAN URL')}</small><code>{window.location.origin}/c/{company.companyId.toLowerCase()}</code><button onClick={() => navigator.clipboard.writeText(`${window.location.origin}/c/${company.companyId.toLowerCase()}`)}>{t('Nusxalash')}</button></section><section><small>{t('KOMPANIYA PUBLIC URL')}</small><code>{window.location.origin}/company/{company.companyId.toLowerCase()}</code><button onClick={() => navigator.clipboard.writeText(`${window.location.origin}/company/${company.companyId.toLowerCase()}`)}>{t('Nusxalash')}</button></section><section className="warning"><small>{t('ESKI NFC ID')}</small><p>{company.sourceCardCode ? t('{code} dan ma’lumot nusxalangan. Asl profil o‘zgarmagan.', { code: company.sourceCardCode }) : t('Bu kompaniya hech bir shaxsiy NFC IDga bog‘lanmagan.')}</p></section></div>}
      </section>

      <aside className="cw-preview"><div className="cw-preview-head"><div><span>{t('JONLI KO‘RISH')}</span><b>{t('Tezkor NFC profil')}</b></div><i>● {t('REAL VAQTDA')}</i></div><div className="cw-iphone"><div className="cw-phone-side left"/><div className="cw-phone-side right"/><div className="cw-phone-screen" style={{ backgroundImage:`linear-gradient(rgba(2,2,2,.42),rgba(2,2,2,.92)),url("${form.coverUrl || '/business-assets/market-interior.jpg'}")` }}><div className="cw-dynamic"><span/><i/></div><div className="cw-phone-status"><b>9:41</b><span>⌁ ▰</span></div><div className="cw-phone-id">◆ {company.companyId}</div><div className="cw-phone-logo">{form.logoUrl ? <img src={form.logoUrl} alt=""/> : form.displayName.slice(0,2).toUpperCase()}</div><h3>{form.displayName}</h3><p>{form.subcategory || form.category} · {form.city}</p><div className="cw-phone-buttons"><button>📞 {t('Qo‘ng‘iroq')}</button><button>✈ Telegram</button></div><div className="cw-phone-items">{topItems.length ? topItems.map((entry) => <div key={entry.id}><img src={entry.imageUrl || form.coverUrl || '/business-assets/market-phone.jpg'} alt=""/><span><b>{entry.name}</b><small>{Number(entry.price).toLocaleString('uz-UZ')} {t('so‘m')}</small></span></div>) : <div className="empty"><span><b>{t(cta.label)}</b><small>{t('Katalog elementlari shu yerda chiqadi')}</small></span></div>}</div><div className="cw-home-indicator"/></div></div><p>{t('Bu preview shaxsiy NFC kontakt kartasi emas. Kompaniya NFC kartasiga aynan shu quick profil yoziladi.')}</p></aside>
    </div>{notice && <div className="cw-toast">{notice}</div>}
  </main>;
}

