/**
 * UZ / RU / EN copy for the Settings, Notifications and NFC screens.
 *
 * The shared dictionary in src/i18n/strings.ts is owned elsewhere and is not
 * edited from here; its keys ('profile.*', 'nfc.*', 'notifications.*',
 * 'common.*') are used through `useT()` wherever they exist, and this file
 * carries only the extra screen-level copy those keys don't cover — in all
 * three languages, so switching the app language visibly changes every line
 * on these screens rather than leaving Uzbek islands behind.
 *
 * Uzbek is the source language; `ru`/`en` are typed as the same key set, so a
 * missing translation is a compile error, never a silent language leak.
 */
import { useLocale, type LocaleCode } from '../../i18n';

const uz = {
  // — Settings —
  settingsSubtitle: 'Hisob, til, xavfsizlik va ilova haqida',
  accountGuest: 'Siz tizimga kirmagansiz',
  accountGuestHint: 'Hisobingizga kiring — ID va sozlamalaringiz tiklanadi.',
  accountLogin: 'Kirish',
  accountPremium: 'Premium hisob',
  accountStandard: 'Oddiy hisob',
  accountIdCount: 'NFC ID',
  accountEmailMissing: 'Email ko‘rsatilmagan',
  sectionAccount: 'Hisob',
  sectionApp: 'Ilova',
  sectionSecurity: 'Xavfsizlik',
  sectionSupport: 'Yordam',
  sectionAbout: 'Ilova haqida',
  rowProfileEdit: 'Profil ma’lumotlari',
  rowMyIds: 'Mening ID‘larim',
  rowNotifications: 'Bildirishnomalar',
  rowNotificationsHint: 'Sovg‘a, auksion, buyurtma',
  rowNfc: 'NFC karta',
  rowNfcHint: 'O‘qish va yozish',
  languageSheetTitle: 'Tilni tanlang',
  languageChanged: 'Til o‘zgartirildi',
  pushRow: 'Push bildirishnomalar',
  pushBackendMissing: 'Server hali yubormaydi',
  pushGranted: 'Ruxsat berilgan',
  pushDenied: 'Ruxsat berilmagan',
  pushUndetermined: 'Ruxsat so‘ralmagan',
  pushUnavailable: 'Qurilmada mavjud emas',
  pushSheetTitle: 'Push bildirishnomalar',
  pushSheetBody:
    'Ilova push qabul qilishga tayyor, lekin serverda push yuborish xizmati hali ulanmagan. Shu sababli hozircha hech qanday push kelmaydi — bildirishnomalar ilova ichida ko‘rsatiladi.',
  pushRequest: 'Ruxsat so‘rash',
  pushDeniedHint: 'Ruxsat rad etilgan. Android sozlamalaridan yoqishingiz mumkin.',
  biometricRow: 'Biometrik qulf',
  biometricOn: 'Yoqilgan',
  biometricOff: 'O‘chirilgan',
  biometricUnavailable: 'Qurilmada mavjud emas',
  biometricNotEnrolled: 'Barmoq izi qo‘shilmagan',
  biometricSheetTitle: 'Biometrik qulf',
  biometricSheetBody:
    'Yoqilsa, Sozlamalar ekrani ochilganda barmoq izi yoki yuz bilan tasdiqlash so‘raladi. Parol yoki token saqlanmaydi — faqat shu sozlama.',
  biometricEnable: 'Yoqish',
  biometricDisable: 'O‘chirish',
  biometricPrompt: 'Sozlamalarni ochish uchun tasdiqlang',
  biometricFailed: 'Tasdiqlanmadi',
  biometricNotEnrolledHint: 'Avval Android sozlamalarida barmoq izi yoki yuzni qo‘shing.',
  lockedTitle: 'Sozlamalar qulflangan',
  lockedBody: 'Davom etish uchun biometrik tasdiqdan o‘ting.',
  unlock: 'Qulfni ochish',
  paymentsRow: 'To‘lovlar',
  paymentsOpen: 'Faol',
  paymentsClosed: 'Yopiq',
  paymentsUnknown: 'Tekshirilmoqda...',
  paymentsSheetTitle: 'To‘lovlar holati',
  paymentsOpenBody: 'To‘lovlar hozir ochiq — ID sotib olish va auksion to‘lovlari ishlaydi.',
  paymentsClosedBody:
    'To‘lov tizimi hozircha yopiq. Sotib olish va auksion to‘lovlari vaqtincha ishlamaydi — bu server sozlamasi, ilovadagi xatolik emas.',
  paymentsRecheck: 'Qayta tekshirish',
  supportTelegram: 'Telegram',
  supportEmail: 'Email',
  supportPhone: 'Telefon',
  supportOpenFailed: 'Ilovani ochib bo‘lmadi',
  versionRow: 'Versiya',
  logoutConfirmTitle: 'Chiqishni tasdiqlang',
  logoutConfirmBody: 'Hisobingizdan chiqmoqchimisiz?',
  logoutConfirm: 'Ha, chiqish',
  logoutFailed: 'Chiqishda xatolik. Qayta urining.',

  // — Notifications —
  notificationsSubtitle: 'Sovg‘alar, auksion va buyurtmalar',
  notificationsMarkRead: 'O‘qilgan deb belgilash',
  notificationsNew: 'Yangi',
  notificationsEmptyHint:
    'Sovg‘a taklifi, yutgan auksion yoki to‘lov kutayotgan buyurtma paydo bo‘lsa — shu yerda ko‘rinadi.',
  notificationsPartialError: 'Ba’zi ma’lumotlarni yuklab bo‘lmadi.',
  notificationsSourceNote: 'Ro‘yxat ilova ochilganda va tortib yangilaganda yangilanadi.',
  giftTitle: 'Sovg‘a taklifi',
  giftBody: '{from} sizga {code} ID’ini sovg‘a qilmoqchi',
  giftFromUnknown: 'Foydalanuvchi',
  giftAccept: 'Qabul qilish',
  giftReject: 'Rad etish',
  giftAccepted: 'Sovg‘a qabul qilindi',
  giftRejected: 'Sovg‘a rad etildi',
  giftActionFailed: 'Amalni bajarib bo‘lmadi',
  auctionWonTitle: 'Auksionda g‘olib bo‘ldingiz',
  auctionWonBody: '{code} — {price}',
  orderPendingTitle: 'To‘lov kutilmoqda',
  orderPaidTitle: 'To‘lov qabul qilindi',
  orderCancelledTitle: 'Buyurtma bekor qilindi',
  orderExpiredTitle: 'Buyurtma muddati tugadi',
  orderBody: '{code} — {price}',
  openLabel: 'Ochish',

  // — NFC —
  nfcTabRead: 'O‘qish',
  nfcTabWrite: 'Yozish',
  nfcReadIntro: 'Telefoningizning orqa qismini NFCSTORE kartaga yaqinlashtiring.',
  nfcStartScan: 'Skanerlashni boshlash',
  nfcStopScan: 'To‘xtatish',
  nfcCancelled: 'Bekor qilindi',
  nfcHardwareReady: 'NFC yoqilgan',
  nfcHardwareDisabled: 'NFC o‘chirilgan',
  nfcHardwareUnsupported: 'NFC yo‘q',
  nfcUnsupportedBody:
    'Bu qurilmada NFC moduli yo‘q (emulyatorlarda ham shunday). Profilingizni havola orqali ulashishingiz mumkin.',
  nfcDisabledBody: 'NFC o‘chirilgan. Android sozlamalaridan yoqing va qayta urining.',
  nfcSettingsFailed: 'Sozlamalarni ochib bo‘lmadi',
  nfcTagUnsupportedBody: 'Bu tegda NFCSTORE profili yoki karta tokeni topilmadi.',
  nfcReadFailed: 'O‘qib bo‘lmadi. Kartani ushlab turing va qayta urining.',
  nfcCardInactive: 'Bu karta faol emas.',
  nfcCardNotLinked: 'Bu karta hali biror ID’ga bog‘lanmagan.',
  nfcSuccessTitle: 'Profil topildi',
  nfcSuccessBody: '{code} ochilmoqda...',
  nfcCheckPending: 'Karta tekshirilmoqda...',
  nfcRetry: 'Qayta urinish',
  nfcWriteIntro: 'Bo‘sh yoki qayta yoziladigan NFC tegga ochiq profil havolangizni yozing.',
  nfcWritePick: 'Qaysi ID yozilsin?',
  nfcWritePickTitle: 'ID tanlang',
  nfcWriteStart: 'Yozishni boshlash',
  nfcWriteWaiting: 'Tegni yaqinlashtiring...',
  nfcWriteNote: 'Faqat ochiq havola yoziladi. Jismoniy kartaning maxfiy tokeni serverda beriladi.',
  nfcWriteNoCards: 'Yozish uchun avval NFC ID kerak.',
  nfcWriteTagUnsupported: 'Bu tegga yozib bo‘lmaydi — himoyalangan yoki formatlanmagan.',
  nfcWriteSuccessBody: '{url} tegga yozildi.',
  nfcWriteAgain: 'Yana yozish',
} as const;

export type ProfileCopyKey = keyof typeof uz;
type Copy = Record<ProfileCopyKey, string>;

const ru: Copy = {
  settingsSubtitle: 'Аккаунт, язык, безопасность и о приложении',
  accountGuest: 'Вы не вошли в аккаунт',
  accountGuestHint: 'Войдите — ваши ID и настройки восстановятся.',
  accountLogin: 'Войти',
  accountPremium: 'Премиум-аккаунт',
  accountStandard: 'Обычный аккаунт',
  accountIdCount: 'NFC ID',
  accountEmailMissing: 'Email не указан',
  sectionAccount: 'Аккаунт',
  sectionApp: 'Приложение',
  sectionSecurity: 'Безопасность',
  sectionSupport: 'Поддержка',
  sectionAbout: 'О приложении',
  rowProfileEdit: 'Данные профиля',
  rowMyIds: 'Мои ID',
  rowNotifications: 'Уведомления',
  rowNotificationsHint: 'Подарки, аукционы, заказы',
  rowNfc: 'NFC-карта',
  rowNfcHint: 'Чтение и запись',
  languageSheetTitle: 'Выберите язык',
  languageChanged: 'Язык изменён',
  pushRow: 'Push-уведомления',
  pushBackendMissing: 'Сервер пока не отправляет',
  pushGranted: 'Разрешено',
  pushDenied: 'Запрещено',
  pushUndetermined: 'Разрешение не запрошено',
  pushUnavailable: 'Недоступно на устройстве',
  pushSheetTitle: 'Push-уведомления',
  pushSheetBody:
    'Приложение готово принимать push, но сервис отправки на сервере ещё не подключён. Поэтому push пока не приходят — уведомления показываются внутри приложения.',
  pushRequest: 'Запросить разрешение',
  pushDeniedHint: 'Разрешение отклонено. Его можно включить в настройках Android.',
  biometricRow: 'Биометрическая защита',
  biometricOn: 'Включена',
  biometricOff: 'Выключена',
  biometricUnavailable: 'Недоступно на устройстве',
  biometricNotEnrolled: 'Отпечаток не добавлен',
  biometricSheetTitle: 'Биометрическая защита',
  biometricSheetBody:
    'Если включить, при открытии Настроек будет запрашиваться отпечаток или распознавание лица. Пароли и токены не сохраняются — только эта настройка.',
  biometricEnable: 'Включить',
  biometricDisable: 'Выключить',
  biometricPrompt: 'Подтвердите, чтобы открыть настройки',
  biometricFailed: 'Не подтверждено',
  biometricNotEnrolledHint: 'Сначала добавьте отпечаток или лицо в настройках Android.',
  lockedTitle: 'Настройки заблокированы',
  lockedBody: 'Для продолжения пройдите биометрическое подтверждение.',
  unlock: 'Разблокировать',
  paymentsRow: 'Платежи',
  paymentsOpen: 'Активны',
  paymentsClosed: 'Закрыты',
  paymentsUnknown: 'Проверяем...',
  paymentsSheetTitle: 'Статус платежей',
  paymentsOpenBody: 'Платежи открыты — покупка ID и оплата аукционов работают.',
  paymentsClosedBody:
    'Платёжная система пока закрыта. Покупка и оплата аукционов временно не работают — это настройка сервера, а не ошибка приложения.',
  paymentsRecheck: 'Проверить снова',
  supportTelegram: 'Telegram',
  supportEmail: 'Email',
  supportPhone: 'Телефон',
  supportOpenFailed: 'Не удалось открыть приложение',
  versionRow: 'Версия',
  logoutConfirmTitle: 'Подтвердите выход',
  logoutConfirmBody: 'Выйти из аккаунта?',
  logoutConfirm: 'Да, выйти',
  logoutFailed: 'Ошибка при выходе. Попробуйте ещё раз.',

  notificationsSubtitle: 'Подарки, аукционы и заказы',
  notificationsMarkRead: 'Отметить прочитанным',
  notificationsNew: 'Новое',
  notificationsEmptyHint:
    'Здесь появятся предложения подарков, выигранные аукционы и заказы, ожидающие оплаты.',
  notificationsPartialError: 'Часть данных не удалось загрузить.',
  notificationsSourceNote: 'Список обновляется при открытии приложения и по жесту «потянуть вниз».',
  giftTitle: 'Предложение подарка',
  giftBody: '{from} хочет подарить вам ID {code}',
  giftFromUnknown: 'Пользователь',
  giftAccept: 'Принять',
  giftReject: 'Отклонить',
  giftAccepted: 'Подарок принят',
  giftRejected: 'Подарок отклонён',
  giftActionFailed: 'Не удалось выполнить действие',
  auctionWonTitle: 'Вы выиграли аукцион',
  auctionWonBody: '{code} — {price}',
  orderPendingTitle: 'Ожидает оплаты',
  orderPaidTitle: 'Оплата получена',
  orderCancelledTitle: 'Заказ отменён',
  orderExpiredTitle: 'Срок заказа истёк',
  orderBody: '{code} — {price}',
  openLabel: 'Открыть',

  nfcTabRead: 'Чтение',
  nfcTabWrite: 'Запись',
  nfcReadIntro: 'Поднесите заднюю часть телефона к карте NFCSTORE.',
  nfcStartScan: 'Начать сканирование',
  nfcStopScan: 'Остановить',
  nfcCancelled: 'Отменено',
  nfcHardwareReady: 'NFC включён',
  nfcHardwareDisabled: 'NFC выключен',
  nfcHardwareUnsupported: 'Нет NFC',
  nfcUnsupportedBody:
    'На этом устройстве нет модуля NFC (как и на эмуляторах). Профилем можно поделиться ссылкой.',
  nfcDisabledBody: 'NFC выключен. Включите его в настройках Android и попробуйте снова.',
  nfcSettingsFailed: 'Не удалось открыть настройки',
  nfcTagUnsupportedBody: 'На этой метке нет профиля NFCSTORE или токена карты.',
  nfcReadFailed: 'Не удалось прочитать. Удерживайте карту и попробуйте снова.',
  nfcCardInactive: 'Эта карта неактивна.',
  nfcCardNotLinked: 'Эта карта ещё не привязана к ID.',
  nfcSuccessTitle: 'Профиль найден',
  nfcSuccessBody: 'Открываем {code}...',
  nfcCheckPending: 'Проверяем карту...',
  nfcRetry: 'Попробовать снова',
  nfcWriteIntro: 'Запишите ссылку на ваш публичный профиль на пустую или перезаписываемую NFC-метку.',
  nfcWritePick: 'Какой ID записать?',
  nfcWritePickTitle: 'Выберите ID',
  nfcWriteStart: 'Начать запись',
  nfcWriteWaiting: 'Поднесите метку...',
  nfcWriteNote: 'Записывается только публичная ссылка. Секретный токен физической карты выдаёт сервер.',
  nfcWriteNoCards: 'Для записи сначала нужен NFC ID.',
  nfcWriteTagUnsupported: 'На эту метку нельзя записать — она защищена или не отформатирована.',
  nfcWriteSuccessBody: '{url} записан на метку.',
  nfcWriteAgain: 'Записать ещё',
};

const en: Copy = {
  settingsSubtitle: 'Account, language, security and app info',
  accountGuest: 'You are not signed in',
  accountGuestHint: 'Sign in to restore your IDs and settings.',
  accountLogin: 'Sign in',
  accountPremium: 'Premium account',
  accountStandard: 'Standard account',
  accountIdCount: 'NFC IDs',
  accountEmailMissing: 'No email on file',
  sectionAccount: 'Account',
  sectionApp: 'App',
  sectionSecurity: 'Security',
  sectionSupport: 'Support',
  sectionAbout: 'About',
  rowProfileEdit: 'Profile details',
  rowMyIds: 'My IDs',
  rowNotifications: 'Notifications',
  rowNotificationsHint: 'Gifts, auctions, orders',
  rowNfc: 'NFC card',
  rowNfcHint: 'Read and write',
  languageSheetTitle: 'Choose a language',
  languageChanged: 'Language changed',
  pushRow: 'Push notifications',
  pushBackendMissing: 'Server does not send yet',
  pushGranted: 'Allowed',
  pushDenied: 'Blocked',
  pushUndetermined: 'Not requested',
  pushUnavailable: 'Unavailable on this device',
  pushSheetTitle: 'Push notifications',
  pushSheetBody:
    'The app is ready to receive push, but no sending service is connected on the server yet. Nothing will arrive for now — notifications are shown inside the app instead.',
  pushRequest: 'Request permission',
  pushDeniedHint: 'Permission was denied. You can enable it in Android settings.',
  biometricRow: 'Biometric lock',
  biometricOn: 'On',
  biometricOff: 'Off',
  biometricUnavailable: 'Unavailable on this device',
  biometricNotEnrolled: 'No fingerprint enrolled',
  biometricSheetTitle: 'Biometric lock',
  biometricSheetBody:
    'When on, opening Settings asks for your fingerprint or face. No password or token is stored — only this preference.',
  biometricEnable: 'Turn on',
  biometricDisable: 'Turn off',
  biometricPrompt: 'Confirm to open settings',
  biometricFailed: 'Not confirmed',
  biometricNotEnrolledHint: 'Add a fingerprint or face in Android settings first.',
  lockedTitle: 'Settings are locked',
  lockedBody: 'Confirm with biometrics to continue.',
  unlock: 'Unlock',
  paymentsRow: 'Payments',
  paymentsOpen: 'Open',
  paymentsClosed: 'Closed',
  paymentsUnknown: 'Checking...',
  paymentsSheetTitle: 'Payment status',
  paymentsOpenBody: 'Payments are open — ID purchases and auction payments work.',
  paymentsClosedBody:
    'The payment system is closed for now. Purchases and auction payments are temporarily unavailable — this is a server setting, not an app error.',
  paymentsRecheck: 'Check again',
  supportTelegram: 'Telegram',
  supportEmail: 'Email',
  supportPhone: 'Phone',
  supportOpenFailed: 'Could not open that app',
  versionRow: 'Version',
  logoutConfirmTitle: 'Confirm sign out',
  logoutConfirmBody: 'Sign out of your account?',
  logoutConfirm: 'Yes, sign out',
  logoutFailed: 'Sign-out failed. Please try again.',

  notificationsSubtitle: 'Gifts, auctions and orders',
  notificationsMarkRead: 'Mark as read',
  notificationsNew: 'New',
  notificationsEmptyHint:
    'Gift offers, auctions you won and orders awaiting payment will show up here.',
  notificationsPartialError: 'Some data could not be loaded.',
  notificationsSourceNote: 'The list refreshes when you open the app and on pull-to-refresh.',
  giftTitle: 'Gift offer',
  giftBody: '{from} wants to gift you ID {code}',
  giftFromUnknown: 'A user',
  giftAccept: 'Accept',
  giftReject: 'Decline',
  giftAccepted: 'Gift accepted',
  giftRejected: 'Gift declined',
  giftActionFailed: 'That action failed',
  auctionWonTitle: 'You won an auction',
  auctionWonBody: '{code} — {price}',
  orderPendingTitle: 'Awaiting payment',
  orderPaidTitle: 'Payment received',
  orderCancelledTitle: 'Order cancelled',
  orderExpiredTitle: 'Order expired',
  orderBody: '{code} — {price}',
  openLabel: 'Open',

  nfcTabRead: 'Read',
  nfcTabWrite: 'Write',
  nfcReadIntro: 'Hold the back of your phone against the NFCSTORE card.',
  nfcStartScan: 'Start scanning',
  nfcStopScan: 'Stop',
  nfcCancelled: 'Cancelled',
  nfcHardwareReady: 'NFC on',
  nfcHardwareDisabled: 'NFC off',
  nfcHardwareUnsupported: 'No NFC',
  nfcUnsupportedBody:
    'This device has no NFC hardware (emulators included). You can still share your profile as a link.',
  nfcDisabledBody: 'NFC is off. Turn it on in Android settings and try again.',
  nfcSettingsFailed: 'Could not open settings',
  nfcTagUnsupportedBody: 'This tag carries no NFCSTORE profile or card token.',
  nfcReadFailed: 'Could not read the tag. Hold it still and try again.',
  nfcCardInactive: 'This card is not active.',
  nfcCardNotLinked: 'This card is not linked to an ID yet.',
  nfcSuccessTitle: 'Profile found',
  nfcSuccessBody: 'Opening {code}...',
  nfcCheckPending: 'Checking the card...',
  nfcRetry: 'Try again',
  nfcWriteIntro: 'Write your public profile link onto a blank or rewritable NFC tag.',
  nfcWritePick: 'Which ID should be written?',
  nfcWritePickTitle: 'Choose an ID',
  nfcWriteStart: 'Start writing',
  nfcWriteWaiting: 'Hold the tag close...',
  nfcWriteNote: 'Only the public link is written. A physical card’s secret token is issued by the server.',
  nfcWriteNoCards: 'You need an NFC ID before you can write a tag.',
  nfcWriteTagUnsupported: 'This tag cannot be written — it is protected or unformatted.',
  nfcWriteSuccessBody: '{url} written to the tag.',
  nfcWriteAgain: 'Write another',
};

const PROFILE_DICTIONARIES: Record<LocaleCode, Copy> = { uz, ru, en };

/** Translate outside React, or for a locale other than the active one — used
 * for the confirmation toast shown *after* a language switch, which must
 * already speak the newly chosen language. */
export function profileText(key: ProfileCopyKey, locale: LocaleCode): string {
  return PROFILE_DICTIONARIES[locale]?.[key] ?? uz[key];
}

/** Subscribes the component to the active locale (same contract as `useT`). */
export function useProfileCopy(): (key: ProfileCopyKey) => string {
  const locale = useLocale();
  return (key) => PROFILE_DICTIONARIES[locale]?.[key] ?? uz[key];
}

/** Fills `{placeholder}` slots. Every value goes through the caller's own
 * `safeText`/`formatSom` first, so a missing field can never render as
 * `undefined` or `[object Object]`. */
export function fill(template: string, values: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(values, key) ? values[key] : match,
  );
}
